# Generated by Django 4.2.15 on 2024-09-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_articleparagraph_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleparagraph',
            options={},
        ),
        migrations.RemoveField(
            model_name='articleparagraph',
            name='order',
        ),
    ]
